ALTER TABLE `User` ADD COLUMN `deletedAt` DATETIME(3) NULL, ADD COLUMN `privacyVersion` VARCHAR(80) NULL, ADD COLUMN `privacyAcceptedAt` DATETIME(3) NULL;
ALTER TABLE `Problem` ADD COLUMN `deletedAt` DATETIME(3) NULL;
ALTER TABLE `Competition` ADD COLUMN `deletedAt` DATETIME(3) NULL;
CREATE TABLE `UserUsage` (
 `userId` VARCHAR(191) NOT NULL, `loginCount` INTEGER NOT NULL DEFAULT 0, `submissionCount` INTEGER NOT NULL DEFAULT 0, `playgroundCount` INTEGER NOT NULL DEFAULT 0, `graderRunCount` INTEGER NOT NULL DEFAULT 0, `lastUsedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `UserAccessLog` (
 `id` VARCHAR(191) NOT NULL, `userId` VARCHAR(191) NOT NULL, `kind` ENUM('LOGIN','SUBMISSION','PLAYGROUND') NOT NULL, `ip` VARCHAR(45) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), INDEX `UserAccessLog_userId_createdAt_idx` (`userId`,`createdAt`), INDEX `UserAccessLog_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `UserUsage` ADD CONSTRAINT `UserUsage_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `UserAccessLog` ADD CONSTRAINT `UserAccessLog_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
